export const routineExercises = [
	{
		id: 1,
		time: "morning",
		image: "src/assets/awaken_6347207.png",
		correctAnswer: "In the morning, I wake up",
		help: "Use 'wake up' to describe this action",
		alt: "wake up",
	},
	{
		id: 2,
		time: "morning",
		image: "src/assets/shower_15341311.png",
		correctAnswer: "In the morning, I take a shower",
		help: "Use 'take a shower' to describe this action",
		alt: "take a shower",
	},
	{
		id: 3,
		time: "morning",
		image: "src/assets/binge-eating_3475150.png",
		correctAnswer: "In the morning, I eat breakfast",
		help: "Use 'eat breakfast' to describe this action",
		alt: "eat",
	},
	{
		id: 4,
		time: "morning",
		image: "src/assets/school.png",
		correctAnswer: "In the morning, I go to school",
		help: "Use 'go to school' to describe this action",
		alt: "go to school",
	},
	{
		id: 5,
		time: "evening",
		image: "src/assets/brush.png",
		correctAnswer: "In the evening, I brush my teeth",
		help: "Use 'brush my teeth' to describe this action",
		alt: "brush my teeth",
	},
	{
		id: 6,
		time: "afternoon",
		image: "src/assets/sleep.png",
		correctAnswer: "In the afternoon, I go to sleep",
		help: "Use 'go to sleep' to describe this action",
		alt: "go to sleep",
	},
];
